=== Rawrisaur/Lab07/timetables.dtd
<!ELEMENT timetables (timeslots,daysofweek,courses)>
	<!ELEMENT timeslots (slot*)>
		<!ELEMENT slot (booking*)>
			<!ATTLIST slot time CDATA #REQUIRED>

	<!ELEMENT daysofweek (day*)>
		<!ELEMENT day (booking*)>
		<!ATTLIST day dow (M|T|W|R|F) #REQUIRED>

	<!ELEMENT courses (course*)>
		<!ELEMENT course (booking*)>
			<!ATTLIST course code CDATA #REQUIRED>

<!ELEMENT booking EMPTY>
	<!ATTLIST booking 
		day (M|T|W|R|F) #IMPLIED
		time CDATA #IMPLIED
		course CDATA #IMPLIED
		room CDATA #REQUIRED
		instructor CDATA #REQUIRED
		type CDATA #REQUIRED
	>

<!ENTITY courses SYSTEM "courses.xml">
<!ENTITY daysofweek SYSTEM "daysofweek.xml">
<!ENTITY timeslots SYSTEM "timeslots.xml">

=== Rawrisaur/Lab07/daysofweek.xml
<?xml version="1.0"?>
<!DOCTYPE daysofweek SYSTEM "timetables.dtd">
<daysofweek>
	<day dow="M">
		<booking time="8:30" course="Comp4560" room="SE12-320" instructor="Brenda Fine" type="Lab" />
		<booking time="11:30" course="Comp4735" room="SW5-1840" instructor="Mirela Gutica" type="Lecture" />
		<booking time="15::30" course="Comp4735" room="SE12-322" instructor="Matt Linder" type="Lab" />
	</day>
	<day dow="T">
		<booking time="12:30" course="Comp4711" room="SE12-320" instructor="Jim Parry" type="Lab" />
		<booking time="13:30" course="Comp4945" room="SE12-319" instructor="Tejinder Randahwa" type="Lecture/Lab" />
		<booking time="14:30" course="Comp4711" room="SW5-1840" instructor="Jim Parry" type="Lecture" />
	</day>
	<day dow="W">
		<booking time="9:30" course="Comp4945" room="SE12-319" instructor="Tejinder Randahwa" type="Lecture/Lab" />
		<booking time="10:30" course="Comp4941" room="SE12-319" instructor="Tejinder Randahwa" type="Lecture/Lab" />
		<booking time="13:30" course="Comp4735" room="SW1-1205" instructor="Mirela Gutica" type="Lecture" />
	</day>
	<day dow="R">
		<booking time="11:30" course="Comp4735" room="SW3-1710" instructor="Mirela Gutica" type="Lecture" />
		<booking time="9:30" course="Blaw3600" room="SW3-3620" instructor="Catherine Ryan" type="Lecture" />
		<booking time="13:30" course="Comp4945" room="SE12-319" instructor="Tejinder Randahwa" type="Lecture/Lab" />
	</day>
	<day dow="F">
		<booking time="8:30" course="Blaw3600" room="SW5-1850" instructor="Catherine Ryan" type="Lecture" />
		<booking time="12:30" course="Comp4560" room="SW1-1021" instructor="Brenda Fine" type="Lecture" />
		<booking time="13:30" course="Comp4941" room="SE12-319" instructor="Tejinder Randahwa" type="Lecture/Lab" />
	</day>
</daysofweek>

=== Rawrisaur/Lab07/timeslots.xml
<?xml version="1.0"?>
<!DOCTYPE timeslots SYSTEM "timetables.dtd">
<timeslots>
	<slot time="8:30">
		<booking day="M" course="Comp4560" room="SE12-320" instructor="Brenda Fine" type="Lab" />
		<booking day="F" course="Blaw3600" room="SW5-1850" instructor="Catherine Ryan" type="Lecture" />
	</slot>	
	<slot time="9:30">
		<booking day="W" course="Comp4945" room="SE12-319" instructor="Tejinder Randahwa" type="Lecture/Lab" />
		<booking day="R" course="Blaw3600" room="SW3-3620" instructor="Catherine Ryan" type="Lecture" />
	</slot>	
	<slot time="10:30">
		<booking day="W" course="Comp4941" room="SE12-319" instructor="Tejinder Randahwa" type="Lecture/Lab" />
	</slot>	
	<slot time="11:30">
		<booking day="M" course="Comp4735" room="SW5-1840" instructor="Mirela Gutica" type="Lecture" />
		<booking day="T" course="Comp4560" room="SW5-1850" instructor="Brenda Fine" type="Lecture" />
		<booking day="R" course="Comp4735" room="SW3-1710" instructor="Mirela Gutica" type="Lecture" />
	</slot>	
	<slot time="12:30">
		<booking day="T" course="Comp4711" room="SE12-320" instructor="Jim Parry" type="Lab" />
		<booking day="F" course="Comp4560" room="SW1-1021" instructor="Brenda Fine" type="Lecture" />
	</slot>	
	<slot time="13:30">
		<booking day="W" course="Comp4735" room="SW1-1205" instructor="Mirela Gutica" type="Lecture" />
		<booking day="R" course="Comp4945" room="SE12-319" instructor="Tejinder Randahwa" type="Lecture/Lab" />
		<booking day="F" course="Comp4941" room="SE12-319" instructor="Tejinder Randahwa" type="Lecture/Lab" />
	</slot>	
	<slot time="14:30">
		<booking day="T" course="Comp4711" room="SW5-1840" instructor="Jim Parry" type="Lecture" />
	</slot>	
	<slot time="15:30">
		<booking day="M" course="Comp4735" room="SE12-322" instructor="Matt Linder" type="Lab" />
	</slot>	
	<slot time="16:30">
	</slot>	
</timeslots>

=== Rawrisaur/Lab07/courses.xml
<?xml version="1.0"?>
<!DOCTYPE courses SYSTEM "timetables.dtd">
<courses>
	<course code="Comp4560">
		<booking time="8:30" day="M" room="SE12-320" instructor="Brenda Fine" type="Lab" />
		<booking time="12:30" day="F" room="SW1-1021" instructor="Brenda Fine" type="Lecture" />
	</course>
	<course code="Comp4711">
		<booking time="12:30" day="T" room="SE12-320" instructor="Jim Parry" type="Lab" />
		<booking time="14:30" day="T" room="SW5-1840" instructor="Jim Parry" type="Lecture" />
	</course>
	<course code="Comp4945">
		<booking time="13:30" day="T" room="SE12-319" instructor="Tejinder Randahwa" type="Lecture/Lab" />
		<booking time="9:30" day="W" room="SE12-319" instructor="Tejinder Randahwa" type="Lecture/Lab" />
		<booking time="13:30" day="R" room="SE12-319" instructor="Tejinder Randahwa" type="Lecture/Lab" />
	</course>
	<course code="Comp4941">
		<booking time="10:30" day="W" room="SE12-319" instructor="Tejinder Randahwa" type="Lecture/Lab" />
		<booking time="13:30" day="F" room="SE12-319" instructor="Tejinder Randahwa" type="Lecture/Lab" />
	</course>
	<course code="Comp4735">
		<booking time="11:30" day="M" room="SW5-1840" instructor="Mirela Gutica" type="Lecture" />
		<booking time="15::30" day="M" room="SE12-322" instructor="Matt Linder" type="Lab" />
		<booking time="11:30"  day="R" room="SW3-1710" instructor="Mirela Gutica" type="Lecture" />
		<booking time="13:30" day="W" room="SW1-1205" instructor="Mirela Gutica" type="Lecture" />
	</course>
	<course code="Blaw3600">
		<booking time="9:30" day="R" room="SW3-3620" instructor="Catherine Ryan" type="Lecture" />
		<booking time="8:30" day="F" room="SW5-1850" instructor="Catherine Ryan" type="Lecture" />
	</course>
</courses>
